// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLkJx2UhorOY-GoHSeUeIz-v4wq8srIkw',
    appId: '1:75413077812:web:257f5f88d1db23f13cef61',
    messagingSenderId: '75413077812',
    projectId: 'mtrms-6101d',
    authDomain: 'mtrms-6101d.firebaseapp.com',
    storageBucket: 'mtrms-6101d.firebasestorage.app',
    measurementId: 'G-3WV65M6R28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD221JI_x9QFMbQsNbigVdAgBkGhuNYPOk',
    appId: '1:75413077812:android:fe78a89ec7e765093cef61',
    messagingSenderId: '75413077812',
    projectId: 'mtrms-6101d',
    storageBucket: 'mtrms-6101d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3T2jRmZryseCWubXHptp3BOIUSkWjK4M',
    appId: '1:75413077812:ios:41bb93c4f684e1643cef61',
    messagingSenderId: '75413077812',
    projectId: 'mtrms-6101d',
    storageBucket: 'mtrms-6101d.firebasestorage.app',
    iosBundleId: 'com.example.rms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3T2jRmZryseCWubXHptp3BOIUSkWjK4M',
    appId: '1:75413077812:ios:41bb93c4f684e1643cef61',
    messagingSenderId: '75413077812',
    projectId: 'mtrms-6101d',
    storageBucket: 'mtrms-6101d.firebasestorage.app',
    iosBundleId: 'com.example.rms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLkJx2UhorOY-GoHSeUeIz-v4wq8srIkw',
    appId: '1:75413077812:web:b1d453042e4b2d683cef61',
    messagingSenderId: '75413077812',
    projectId: 'mtrms-6101d',
    authDomain: 'mtrms-6101d.firebaseapp.com',
    storageBucket: 'mtrms-6101d.firebasestorage.app',
    measurementId: 'G-7Z73PT4MYM',
  );
}
